=== spitemonster/cms/server/schema/page.schema.json
{
    "$schema" : "http://json-schema.org/draft-07/schema#",
    "$id" : "./page.schema.json",
    "title" : "Page",
    "description" : "A page on the site",
    "type" : "object",
    "properties" : {
        "id" : {
            "description" : "A page's unique ID",
            "type" : "string",
            "format" : "uuid"
        },
        "updatedBy" : {
            "description" : "Username of most recent user to make changes to the page",
            "type" : "string"
        },
        "createdBy" : {
            "description" : "Username of user that created the page",
            "type" : "string"
        },
        "updatedAt" : {
            "description" : "Date of most recent update",
            "type" : "integer"
        },
        "createdAt" : {
            "description" : "Date the page was created",
            "type" : "integer"
        },
        "name" : {
            "description" : "Name of the page",
            "type" : "string"
        },
        "url" : {
            "description" : "Url desired by the user for the page",
            "type" : "string"
        },
        "templateUrl" : {
            "description" : "Absolute path to template tied to the page",
            "type" : "string",
            "format" : "uri-reference"
        },
        "templateId" : {
            "description" : "Unique ID of the template tied to the page",
            "type" : "string",
            "format" : "uuid"
        },
        "fields" : {
            "description" : "A collection of fields and data for the page",
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties" : {
                    "id" : {
                        "description" : "ID of the field",
                        "type" : "string",
                        "format" : "uuid"
                    },
                    "name" : {
                        "description" : "Name of field",
                        "type" : "string"
                    },
                    "type" : {
                        "description" : "Type of field",
                        "type" : "string"
                    },
                    "required" : {
                        "description" : "Whether or not the field is required",
                        "type" : "boolean"
                    },
                    "content" : {
                        "description" : "Content of field",
                        "type" : "string"
                    }
                },
                "additionalProperties" : false
            },
            "uniqueItems" : true
        },
        "filename" : {
            "description" : "Filename for the page, correlates to page folder and data file",
            "type" : "string"
        },
        "revisions" : {
            "descriptions" : "A collection of revisions organized",
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties": {
                    "id" : {
                        "description" : "ID of the revision",
                        "type" : "string",
                        "format": "uuid"
                    },
                    "updatedBy" : {
                        "description" : "Last user to make changes to page",
                        "type" : "string"
                    },
                    "createdAt" : {
                        "description" : "Creation date of the revision",
                        "type" : "integer"
                    },
                    "name" : {
                        "description" : "Name of the new revision",
                        "type" : "string"
                    }
                },
                "additionalProperties" : false
            }
        }
    },
    "additionalProperties" : false,
    "required" : ["id", "updatedBy", "createdBy", "updatedAt", "createdAt", "name", "url", "templateUrl", "templateId", "fields", "filename"]
}

=== spitemonster/cms/pages/bio/bio.json
{
  "id": "886fbd23-8eb0-4383-97c6-6ab30d5e1c57",
  "updatedBy": "kjohnston",
  "createdBy": "kjohnston",
  "updatedAt": 1550181314817,
  "createdAt": 1550181314817,
  "name": "Bio",
  "url": "/bio",
  "templateUrl": "/Users/kirbyjohnston/sites/cms/server/routes/../../views/templates/home/home.hbs",
  "templateId": "f71d95a6-c756-4819-888c-e41aec565862",
  "fields": [
    {
      "id": "a0e8ac34-d828-49b0-acac-35626173ff96",
      "name": "Title",
      "type": "text",
      "required": true,
      "content": "Bio"
    },
    {
      "id": "a957a58e-f819-475b-877d-1c432182e070",
      "name": "Body",
      "type": "wysiwyg",
      "required": true,
      "content": "<p>Bio</p>"
    }
  ],
  "filename": "bio"
}
